# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='Upload',
            field=models.FileField(default='infiles/TEST.mrc', upload_to='infiles'),
        ),
    ]
