# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 19:15
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_conversion_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='Output',
            field=models.FileField(default='outfiles/TEST.mrc', storage=django.core.files.storage.FileSystemStorage(base_url='/data', location='/data/'), upload_to='outfiles/'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='Upload',
            field=models.FileField(default='infiles/TEST.mrc', storage=django.core.files.storage.FileSystemStorage(base_url='/data', location='/data/'), upload_to='infiles/'),
        ),
    ]
