# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20171206_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='Type',
            field=models.TextField(choices=[('ER_EAI_2nd', 'ER_EAI_2nd'), ('ER_CHOICE2', 'ER_CHOICE2')]),
        ),
    ]
