# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_auto_20171207_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='Type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'ER_EAI_1st'), (2, 'ER_EAI_2nd'), (3, 'ER_OECD')], default=0),
        ),
    ]
