# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 17:33
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_auto_20171207_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='Upload',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/data', location='/data/'), upload_to='infiles/'),
        ),
    ]
