# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_auto_20171208_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='RecordsIn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversion',
            name='RecordsOut',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
