# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 21:31
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_auto_20171219_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='Output',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='', location='/code/batchcave/converter/'), upload_to='outfiles/'),
        ),
    ]
